name: CI

on:
  push:
    paths:
      - '*'
      - '*/**'

env:
  CI: true

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''