name: CI

on:
  push:
    paths:
      - '*'
      - '*/**'

env:
  CI: true

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pump tag to GitHub
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.1
          VERBOSE: true